ignore:
  - "src/RecipeCatalog.BlazorApp/Components/Account"
  - "src/RecipeCatalog.BlazorApp.Client/Components/RedirectToLogin.razor"
  - "src/RecipeCatalog.BlazorApp.Client/PersistentAuthenticationStateProvider.cs"
  - "src/RecipeCatalog.BlazorApp.Client/UserInfo.cs"
  - "src/RecipeCatalog.Domain/Migrations"
